// <auto-generated />
using System;
using MarioMaker2Overlay.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarioMaker2Overlay.Migrations
{
    [DbContext(typeof(MarioMaker2OverlayContext))]
    partial class MarioMaker2OverlayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("MarioMaker2Overlay.Persistence.LevelData", b =>
                {
                    b.Property<int>("LevelDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClearCondition")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClearConditionMagnitude")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTimeUploaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameStyle")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeElapsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGlobalAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGlobalClears")
                        .HasColumnType("INTEGER");

                    b.HasKey("LevelDataId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LevelData");
                });
#pragma warning restore 612, 618
        }
    }
}
